const $=id=>document.getElementById(id);let last=null;
async function api(url,opt={}){let r=await fetch(url,{credentials:"same-origin",...opt});let d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.detail||"Request failed");return d}
function esc(s){return String(s).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
function add(text,type="assistant",meta=""){let row=document.createElement("div");row.className="row "+type;row.innerHTML=`<div class="bubble"><span class="label">${type==="user"?"USER":"QWEN"}</span>${esc(text)}${meta?`<div class="meta">${meta}</div>`:""}</div>`;$("messages").append(row);$("messages").scrollTop=$("messages").scrollHeight}
async function docs(){let d=await api("/api/documents");$("docCount").textContent=d.documents.length+" DOCS";$("chunks").textContent=d.total_chunks;$("docs").innerHTML=d.documents.length?d.documents.map(x=>`<div class="doc">${esc(x.filename)}<small>${x.chunks} CHUNKS · ${(x.size_bytes/1024).toFixed(1)} KB</small></div>`).join(""):`<div class="empty">NO DOCUMENTS INDEXED</div>`}
async function upload(fs){let f=new FormData();[...fs].forEach(x=>f.append("files",x));$("status").textContent="● INDEXING";try{let d=await api("/api/upload",{method:"POST",body:f});await docs();d.results.forEach(x=>add(`${x.filename}: ${x.status}${x.chunks?` (${x.chunks} chunks)`:""}`));$("status").textContent="● SYSTEM READY"}catch(e){add("Upload failed: "+e.message);$("status").textContent="● ERROR"}}
$("files").onchange=e=>upload(e.target.files);$("drop").onclick=()=>$("files").click();$("drop").ondragover=e=>{e.preventDefault();$("drop").style.borderColor="#00ea64"};$("drop").ondrop=e=>{e.preventDefault();upload(e.dataTransfer.files)};
$("clearDocs").onclick=async()=>{if(confirm("Clear knowledge base?")){await api("/api/documents",{method:"DELETE"});await docs()}};
async function send(){let q=$("query").value.trim();if(!q)return;$("query").value="";$("welcome")?.remove();add(q,"user");$("status").textContent="● QWEN PROCESSING";try{let d=await api("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({query:q,hf_token:sessionStorage.getItem("hf_token")})});last=d;add(d.answer,"assistant",`${d.retrieved.length} CHUNKS · ${d.provider} · ${d.retrieved.length?"INSPECT RAG":"NO CONTEXT"}`);$("status").textContent=d.provider==="huggingface-api"?"● HF INFERENCE ONLINE":"● LOCAL FALLBACK"}catch(e){add("Inference failed: "+e.message);$("status").textContent="● ERROR"}}
$("send").onclick=send;$("query").onkeydown=e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}};
$("settings").onclick=()=>$("settingsModal").classList.remove("hidden");$("inspect").onclick=()=>{if(!last)return;renderInspect();$("inspectModal").classList.remove("hidden")};
document.querySelectorAll("[data-close]").forEach(x=>x.onclick=()=>$(x.dataset.close).classList.add("hidden"));
$("saveToken").onclick=async()=>{let t=$("token").value.trim();if(!t)return;$("token").value="";sessionStorage.setItem("hf_token",t);await api("/api/token",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({hf_token:t})});$("tokenStatus").textContent="● SESSION TOKEN CONFIGURED"};
$("removeToken").onclick=async()=>{sessionStorage.removeItem("hf_token");await api("/api/token",{method:"DELETE"});$("tokenStatus").textContent="● USING SERVER CONFIGURATION"};
$("promptTab").onclick=()=>{$("rawPrompt").classList.remove("hidden");$("retrieval").classList.add("hidden")};
$("retrievalTab").onclick=()=>{$("rawPrompt").classList.add("hidden");$("retrieval").classList.remove("hidden")};
function renderInspect(){$("rawPrompt").textContent=last.raw_prompt||"";$("retrieval").innerHTML=(last.retrieved||[]).map(x=>`<div class="card"><span class="score">COSINE ${x.score}</span><small>#${x.rank} · ${esc(x.document)}${x.page?` · PAGE ${x.page}`:""}</small><p>${esc(x.text)}</p></div>`).join("")||"<div class=empty>NO RETRIEVED CHUNKS</div>"}
$("clearChat").onclick=async()=>{await api("/api/chat",{method:"DELETE"});$("messages").innerHTML="";add("Chat history cleared.","assistant")};
(async()=>{await api("/api/session",{method:"POST"});await docs()})()
